### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Taknax** [Luisxcaliber/CaliberDrinksMod3#3]
The spawn rate of the bushes is to high. it should be maybe the half.
Its causing often worldgen cascading lag in the server console.
I use 1.12.2 with 14.23.5.2855 on client and server.
CalierDrinnk 2.0.

**Comment by Luisxcaliber** [comment]
Yes I am aware that the worldgen in the mod is causing lag, I plan on fixing this in the new update of the mod, I sort of taken a break from working on it but I'll start getting back to work on it. Thank you for the post and bringing this back to my attention.

**Comment by Taknax** [comment]
Maybe you can replace air above the gras. Should be stop. Ty for your nice wok.
